#!/usr/bin/env node

/**
 * Renders site.json into every surface that describes the site to a machine.
 *
 * Usage: node scripts/update-seo.js [--check]
 *
 * Outputs:
 *   - llms.txt          agent-readable summary of the site, its projects and
 *                       the consultancy behind it
 *   - sitemap.xml       every real page, with lastmod from the filesystem
 *   - index.html        the Projects list, and the Person / Organization /
 *                       WebSite structured data
 *   - every page        canonical, OpenGraph and Twitter card tags, derived
 *                       from the page's own <title> and description
 *
 * Why a generator instead of hand-edited tags: the same facts were previously
 * repeated in the homepage markup, the sitemap and the structured data, and
 * they had already drifted apart. One manifest, one render, no drift.
 *
 * A note on llms.txt: as of 2026 the major AI crawlers (GPTBot, ClaudeBot,
 * PerplexityBot) overwhelmingly ignore it and read the HTML instead, and Google
 * has declined to support it. It is published here because it is cheap, it is
 * the emerging convention for agent-to-site routing, and it costs one file --
 * NOT because it is what makes the site legible to models. The per-page
 * metadata and JSON-LD below are what actually does that work.
 *
 * --check exits non-zero if anything is out of date, without writing.
 */

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const { escapeHtml, escapeMarkdownInline, safeUrl, jsonLdScript, writeFileAtomic, replaceBlock } = require('./lib');

const ROOT = path.join(__dirname, '..');
const SITE = JSON.parse(fs.readFileSync(path.join(ROOT, 'site.json'), 'utf8'));
const BASE = SITE.site.url.replace(/\/$/, '');

// Pages that are deliberately excluded from discovery surfaces.
const SKIP_PAGES = new Set(['404.html']);
const SKIP_DIRS = new Set(['.git', 'node_modules', '.playwright-mcp', '.github', 'assets', 'videos', 'posts', 'book-notes', 'skills', 'scripts']);

let changed = 0;
const CHECK = process.argv.includes('--check');

// ---------------------------------------------------------------------------
// Shared helpers
// ---------------------------------------------------------------------------


function writeIfChanged(filePath, contents) {
  const rel = path.relative(ROOT, filePath);
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : null;
  if (current === contents) return false;

  changed++;
  if (CHECK) {
    console.log(`  out of date  ${rel}`);
    return true;
  }
  writeFileAtomic(filePath, contents);
  console.log(`  wrote        ${rel}`);
  return true;
}


function findHtmlFiles(dir, found = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      findHtmlFiles(path.join(dir, entry.name), found);
    } else if (entry.isFile() && entry.name.endsWith('.html') && !SKIP_PAGES.has(entry.name)) {
      found.push(path.join(dir, entry.name));
    }
  }
  return found;
}

/** "/blog/x/index.html" -> "/blog/x/";  "/about.html" -> "/about.html" */
function urlPathFor(filePath) {
  const rel = path.relative(ROOT, filePath).split(path.sep).join('/');
  if (rel === 'index.html') return '/';
  if (rel.endsWith('/index.html')) return '/' + rel.slice(0, -'index.html'.length);
  return '/' + rel;
}

function readTag(html, re, group = 1) {
  const m = html.match(re);
  return m ? m[group].trim() : null;
}

// ---------------------------------------------------------------------------
// 1. Per-page discovery tags
//
// Derived from what each page already declares, so adding a page needs no
// configuration: give it a <title> and a description and it is covered.
// ---------------------------------------------------------------------------

const META_START = '<!-- seo:start (generated by scripts/update-seo.js) -->';
const META_END = '<!-- seo:end -->';

function renderPageMeta(page) {
  const lines = [
    `    <link rel="canonical" href="${escapeHtml(page.url)}">`,
    `    <meta property="og:type" content="${page.isArticle ? 'article' : 'website'}">`,
    `    <meta property="og:site_name" content="${escapeHtml(SITE.site.title)}">`,
    `    <meta property="og:url" content="${escapeHtml(page.url)}">`,
    `    <meta property="og:title" content="${escapeHtml(page.title)}">`,
    `    <meta property="og:description" content="${escapeHtml(page.description)}">`,
    `    <meta property="og:image" content="${escapeHtml(page.image)}">`,
    `    <meta property="og:locale" content="en_CA">`,
    `    <meta name="twitter:card" content="summary_large_image">`,
    `    <meta name="twitter:site" content="${escapeHtml(SITE.site.twitter)}">`,
    `    <meta name="twitter:creator" content="${escapeHtml(SITE.site.twitter)}">`,
    `    <meta name="twitter:title" content="${escapeHtml(page.title)}">`,
    `    <meta name="twitter:description" content="${escapeHtml(page.description)}">`,
    `    <meta name="twitter:image" content="${escapeHtml(page.image)}">`,
    `    <meta name="author" content="${escapeHtml(SITE.person.name)}">`
  ];
  return '\n' + lines.join('\n') + '\n    ';
}

function pageFacts(filePath, html) {
  const urlPath = urlPathFor(filePath);
  const rawTitle = readTag(html, /<title>([\s\S]*?)<\/title>/i) || SITE.site.title;
  const description =
    readTag(html, /<meta\s+name="description"\s+content="([^"]*)"/i) ||
    readTag(html, /<meta\s+property="og:description"\s+content="([^"]*)"/i) ||
    SITE.site.tagline;
  // A page's own og:image wins -- book pages legitimately use a cover image.
  const existingImage = readTag(html, /<meta\s+property="og:image"\s+content="([^"]*)"/i);
  return {
    url: BASE + urlPath,
    urlPath,
    title: rawTitle.replace(/\s+/g, ' ').trim(),
    description: description.replace(/\s+/g, ' ').trim(),
    image: existingImage && !existingImage.includes('/og.png') ? existingImage : SITE.site.image,
    isArticle: urlPath.startsWith('/blog/') && urlPath !== '/blog/'
  };
}

/** Insert the marker pair just before </head> the first time a page is seen. */
function ensureMetaMarkers(html) {
  if (html.includes(META_START)) return html;
  const headClose = html.indexOf('</head>');
  if (headClose === -1) return null;
  return html.slice(0, headClose) + `    ${META_START}${META_END}\n` + html.slice(headClose);
}

/**
 * Existing hand-written canonical/og/twitter tags outside our block would
 * duplicate the generated ones. Strip them so each page declares each fact once.
 *
 * The page is split around the generated block and only the parts outside it are
 * rewritten. Matching on offsets instead would be wrong: each chained replace
 * shifts every later offset, so they stop lining up with the marker positions.
 */
const LEGACY_TAG_RE = [
  /^[ \t]*<link\s+rel="canonical"[^>]*>\r?\n?/gim,
  /^[ \t]*<meta\s+property="og:[^"]*"[^>]*>\r?\n?/gim,
  /^[ \t]*<meta\s+name="twitter:[^"]*"[^>]*>\r?\n?/gim
];

function stripOutsideBlock(text) {
  return LEGACY_TAG_RE.reduce((acc, re) => acc.replace(re, ''), text);
}

function stripLegacyTags(html) {
  const start = html.indexOf(META_START);
  const end = html.indexOf(META_END);
  if (start === -1 || end === -1) return stripOutsideBlock(html);

  const before = html.slice(0, start);
  const ours = html.slice(start, end + META_END.length);
  const after = html.slice(end + META_END.length);
  return stripOutsideBlock(before) + ours + stripOutsideBlock(after);
}

function updatePageMeta(filePath) {
  let html = fs.readFileSync(filePath, 'utf8');

  // Read the page's own facts before stripping anything.
  const facts = pageFacts(filePath, html);

  const withMarkers = ensureMetaMarkers(html);
  if (withMarkers === null) {
    console.warn(`  WARNING      ${path.relative(ROOT, filePath)} has no </head>; skipped`);
    return;
  }
  html = stripLegacyTags(withMarkers);
  html = replaceBlock(html, META_START, META_END, renderPageMeta(facts), 'seo');

  writeIfChanged(filePath, html);
}

// ---------------------------------------------------------------------------
// 2. Homepage: Projects list + structured data
// ---------------------------------------------------------------------------

const PROJECTS_START = '<!-- projects:start (generated by scripts/update-seo.js from site.json) -->';
const PROJECTS_END = '<!-- projects:end -->';
const JSONLD_START = '<!-- jsonld:start (generated by scripts/update-seo.js from site.json) -->';
const JSONLD_END = '<!-- jsonld:end -->';

function renderProjects() {
  const items = SITE.projects.map(p => `                    <li>
                        <a href="${escapeHtml(p.url)}">${escapeHtml(p.name)}</a>
                        <span class="meta">${escapeHtml(p.meta)}</span>
                    </li>`).join('\n');
  return `\n                <ul class="link-list">\n${items}\n                </ul>\n                `;
}

/**
 * Structured data is the part AI answer engines and Google actually consume.
 * Person establishes who Peter is, Organization + its service catalogue make
 * Techimpossible answerable to "who does SOC 2 readiness in Vancouver", and
 * ProfilePage ties the site to the person rather than to a brand.
 */
function renderJsonLd() {
  const graph = [
    {
      '@type': 'WebSite',
      '@id': `${BASE}/#website`,
      url: `${BASE}/`,
      name: SITE.site.title,
      description: SITE.site.summary,
      inLanguage: 'en',
      publisher: { '@id': `${BASE}/#person` }
    },
    {
      '@type': 'Person',
      '@id': `${BASE}/#person`,
      name: SITE.person.name,
      alternateName: SITE.person.alternateName,
      url: `${BASE}/`,
      image: SITE.person.photo,
      jobTitle: SITE.person.jobTitle,
      description: SITE.site.summary,
      email: `mailto:${SITE.contact.email}`,
      knowsAbout: SITE.person.expertise,
      nationality: { '@type': 'Country', name: SITE.person.origin },
      workLocation: {
        '@type': 'Place',
        address: {
          '@type': 'PostalAddress',
          addressLocality: 'Vancouver',
          addressRegion: 'BC',
          addressCountry: 'CA'
        }
      },
      worksFor: { '@id': `${BASE}/#organization` },
      sameAs: SITE.person.profiles,
      mainEntityOfPage: `${BASE}/about.html`
    },
    {
      '@type': 'Organization',
      '@id': `${BASE}/#organization`,
      name: SITE.business.name,
      legalName: SITE.business.legalName,
      url: SITE.business.url,
      description: SITE.business.description,
      areaServed: SITE.business.areaServed,
      founder: { '@id': `${BASE}/#person` },
      knowsAbout: SITE.person.expertise,
      hasOfferCatalog: {
        '@type': 'OfferCatalog',
        name: `${SITE.business.name} services`,
        itemListElement: SITE.business.services.map(s => ({
          '@type': 'Offer',
          itemOffered: {
            '@type': 'Service',
            name: s.name,
            description: s.description,
            provider: { '@id': `${BASE}/#organization` }
          }
        }))
      }
    },
    {
      '@type': 'ProfilePage',
      '@id': `${BASE}/#profilepage`,
      url: `${BASE}/`,
      mainEntity: { '@id': `${BASE}/#person` },
      isPartOf: { '@id': `${BASE}/#website` }
    },
    {
      '@type': 'ItemList',
      '@id': `${BASE}/#projects`,
      name: 'Projects',
      itemListElement: SITE.projects.map((p, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: p.name,
        description: p.description,
        url: p.url
      }))
    }
  ];

  const json = jsonLdScript({ '@context': 'https://schema.org', '@graph': graph })
    .split('\n')
    .map(line => '    ' + line)
    .join('\n');

  return `\n    <script type="application/ld+json">\n${json}\n    </script>\n    `;
}

function updateHomepage() {
  const filePath = path.join(ROOT, 'index.html');
  let html = fs.readFileSync(filePath, 'utf8');
  html = replaceBlock(html, PROJECTS_START, PROJECTS_END, renderProjects(), 'projects');
  html = replaceBlock(html, JSONLD_START, JSONLD_END, renderJsonLd(), 'jsonld');
  writeIfChanged(filePath, html);
}

// ---------------------------------------------------------------------------
// 3. llms.txt
// ---------------------------------------------------------------------------

function loadRecentPosts(limit) {
  try {
    const posts = JSON.parse(fs.readFileSync(path.join(ROOT, 'blog-posts.json'), 'utf8'));
    return posts
      .filter(p => p && p.title && p.url && p.date)
      .sort((a, b) => String(b.date).localeCompare(String(a.date)))
      .slice(0, limit);
  } catch (err) {
    console.warn(`  WARNING      could not read blog-posts.json: ${err.message}`);
    return [];
  }
}

function renderLlmsTxt() {
  // Name and description are escaped for markdown, not just the URL. A feed
  // title containing "](javascript:...)" would otherwise close the link early
  // and supply its own destination on a page written for agents to follow.
  const link = (name, url, description) =>
    `- [${escapeMarkdownInline(name)}](${url})` +
    `${description ? `: ${escapeMarkdownInline(description)}` : ''}`;

  const out = [];
  out.push(`# ${SITE.person.name}`);
  out.push('');
  out.push(`> ${SITE.site.summary}`);
  out.push('');
  out.push(
    `${SITE.person.name} is a ${SITE.person.jobTitle} based in ${SITE.person.location}, ` +
    `originally from ${SITE.person.origin}, and the founder of ${SITE.business.name}. ` +
    `He works on ${SITE.person.expertise.slice(0, 6).join(', ')}. ` +
    `Contact: ${SITE.contact.email}.`
  );
  out.push('');

  out.push(`## ${SITE.business.name}`);
  out.push('');
  out.push(SITE.business.description);
  out.push('');
  out.push(`Website: ${SITE.business.url}. Area served: ${SITE.business.areaServed}.`);
  out.push('');
  for (const s of SITE.business.services) out.push(`- **${s.name}**: ${s.description}`);
  out.push('');

  out.push('## Writing');
  out.push('');
  for (const w of SITE.writing) out.push(link(w.name, w.url, w.description));
  out.push('');

  const recent = loadRecentPosts(10);
  if (recent.length) {
    out.push('## Recent posts');
    out.push('');
    for (const p of recent) {
      // Same URL rule as every HTML sink. llms.txt is text/plain so there is no
      // XSS here, but this file exists to be read by agents -- publishing a
      // javascript: destination as site-endorsed is its own problem.
      const url = safeUrl(p.url.startsWith('http') ? p.url : BASE + p.url);
      if (!url) {
        console.warn(`  WARNING      dropped unsafe URL for "${p.title}": ${p.url}`);
        continue;
      }
      out.push(link(p.title, url, `${p.date}${p.description ? ` — ${p.description}` : ''}`));
    }
    out.push('');
  }

  out.push('## Projects');
  out.push('');
  for (const p of SITE.projects) out.push(link(p.name, p.url, p.description));
  out.push('');

  out.push('## Reading');
  out.push('');
  for (const r of SITE.reading) out.push(link(r.name, r.url, r.description));
  out.push('');

  out.push('## Optional');
  out.push('');
  out.push(link('About', `${BASE}/about.html`, 'Background, and why he writes about invisible constraints.'));
  out.push(link('Now', `${BASE}/now.html`, 'What he is focused on at the moment.'));
  out.push('');

  return out.join('\n');
}

// ---------------------------------------------------------------------------
// 4. sitemap.xml
// ---------------------------------------------------------------------------

/**
 * Last commit date for a path, falling back to file mtime.
 *
 * mtime alone is wrong in CI: a fresh actions/checkout stamps every file with
 * the clone time, so all 35 pages claimed to change on every run -- a false
 * freshness signal to exactly the crawlers this file exists to serve, plus a
 * guaranteed daily auto-commit of a sitemap nobody edited.
 */
function lastModified(filePath) {
  try {
    const out = execFileSync('git', ['log', '-1', '--format=%cI', '--', filePath], {
      cwd: ROOT,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
    if (out) return out.slice(0, 10);
  } catch (err) {
    // Not a git checkout, or the file is untracked: fall through.
  }
  return fs.statSync(filePath).mtime.toISOString().slice(0, 10);
}

function renderSitemap(pages) {
  const urls = pages
    .map(p => {
      const lastmod = lastModified(p.filePath);
      return `  <url>\n    <loc>${escapeHtml(p.url)}</loc>\n    <lastmod>${lastmod}</lastmod>\n  </url>`;
    })
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/update-seo.js. Do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

// ---------------------------------------------------------------------------

function main() {
  console.log(CHECK ? 'Checking discovery surfaces...' : 'Rendering discovery surfaces from site.json...');

  // Homepage blocks first, so its Projects list is present before it is scanned.
  updateHomepage();

  const files = findHtmlFiles(ROOT).sort();
  for (const f of files) updatePageMeta(f);

  const pages = files
    .map(filePath => ({ filePath, url: BASE + urlPathFor(filePath) }))
    .sort((a, b) => a.url.localeCompare(b.url));

  writeIfChanged(path.join(ROOT, 'sitemap.xml'), renderSitemap(pages));
  writeIfChanged(path.join(ROOT, 'llms.txt'), renderLlmsTxt());

  console.log(
    `\nSEO: ${files.length} pages, ${pages.length} sitemap entries, ` +
    `${SITE.projects.length} projects, ${SITE.business.services.length} services. ` +
    `${changed} file(s) ${CHECK ? 'out of date' : 'written'}.`
  );

  if (CHECK && changed > 0) {
    console.error('\nDiscovery surfaces are stale. Run: node scripts/update-seo.js');
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { renderLlmsTxt, renderJsonLd, renderProjects, urlPathFor, pageFacts, safeMarkers: { META_START, META_END } };
