#!/usr/bin/env node

/**
 * Keeps one footer on every page.
 *
 * Usage: node scripts/update-footer.js [--check]
 *
 * The footer had drifted into five variants: library.html had lost its LinkedIn
 * link, claude-skills.html had lost the flag, some pages used relative hrefs
 * that broke at /blog/<slug>/ depth, and the .with-border class was applied at
 * random. This script owns the markup and rewrites it everywhere.
 *
 * It runs LAST in CI, after update-blog.js and update-library.js, so pages those
 * scripts generate get normalised too and their templates need no changes.
 *
 * --check exits non-zero if any page is out of date, without writing.
 */

const fs = require('fs');
const path = require('path');
const { writeFileAtomic } = require('./lib');

const ROOT = path.join(__dirname, '..');

const START = '<!-- site-footer:start (generated by scripts/update-footer.js) -->';
const END = '<!-- site-footer:end -->';

// Full-screen self-contained pages. They deliberately have no site chrome, and
// bolting a footer onto them would overlay the game UI.
const SKIP_FILES = new Set([
  'cyber.html',
  'veridis-quo.html',
  'mazo/index.html'
]);

const SKIP_DIRS = new Set(['.git', 'node_modules', '.playwright-mcp', '.github', 'assets', 'videos']);

// Absolute hrefs only: the same block has to work at /, /blog/<slug>/ and
// /library/<slug>/. Relative paths were the reason nested pages drifted.
const FOOTER_LINKS = [
  { href: '/', label: 'Home' },
  { href: '/about', label: 'About' },
  { href: '/now', label: 'Now' },
  { href: 'https://x.com/peter_skaronis', label: 'Twitter' },
  { href: 'https://www.linkedin.com/in/peterskaronis/', label: 'LinkedIn' }
];

const COPYRIGHT = 'Made in Vancouver \u{1F1E8}\u{1F1E6}';

function renderFooter(indent = '    ') {
  const links = FOOTER_LINKS
    .map(l => `${indent}        <a href="${l.href}">${l.label}</a>`)
    .join('\n');

  return [
    `${indent}${START}`,
    `${indent}<footer class="with-border">`,
    `${indent}    <div class="footer-links">`,
    links,
    `${indent}    </div>`,
    `${indent}    <p class="copyright">${COPYRIGHT}</p>`,
    `${indent}</footer>`,
    `${indent}${END}`
  ].join('\n');
}

function findHtmlFiles(dir, found = []) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      if (SKIP_DIRS.has(entry.name)) continue;
      findHtmlFiles(path.join(dir, entry.name), found);
    } else if (entry.isFile() && entry.name.endsWith('.html')) {
      found.push(path.join(dir, entry.name));
    }
  }
  return found;
}

// Matches a whole <footer>...</footer> element plus the indentation on its line.
const FOOTER_RE = /([ \t]*)<footer\b[^>]*>[\s\S]*?<\/footer>/;
const MARKED_RE = new RegExp(
  `([ \\t]*)${START.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${END.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`
);

function countOccurrences(haystack, needleRe) {
  return (haystack.match(new RegExp(needleRe.source, 'g')) || []).length;
}

function processFile(filePath, { check }) {
  const rel = path.relative(ROOT, filePath);
  if (SKIP_FILES.has(rel)) return { rel, status: 'skipped' };

  const html = fs.readFileSync(filePath, 'utf8');

  // Already migrated: rewrite whatever sits between the markers.
  if (MARKED_RE.test(html)) {
    const indent = html.match(MARKED_RE)[1] || '    ';
    const updated = html.replace(MARKED_RE, renderFooter(indent));
    if (updated === html) return { rel, status: 'current' };
    if (!check) writeFileAtomic(filePath, updated);
    return { rel, status: 'updated' };
  }

  const footerCount = countOccurrences(html, /<footer\b/);
  if (footerCount === 0) {
    // Never guess where a footer belongs. Report and move on.
    return { rel, status: 'no-footer' };
  }
  if (footerCount > 1) {
    return { rel, status: 'ambiguous' };
  }

  const indent = html.match(FOOTER_RE)[1] || '    ';
  const updated = html.replace(FOOTER_RE, renderFooter(indent));
  if (updated === html) return { rel, status: 'current' };
  if (!check) writeFileAtomic(filePath, updated);
  return { rel, status: 'migrated' };
}

function main() {
  const check = process.argv.includes('--check');
  const files = findHtmlFiles(ROOT).sort();

  const results = files.map(f => processFile(f, { check }));
  const by = status => results.filter(r => r.status === status);

  for (const r of results) {
    if (r.status === 'updated' || r.status === 'migrated') {
      console.log(`  ${r.status.padEnd(8)} ${r.rel}`);
    }
  }

  for (const r of by('no-footer')) {
    console.warn(`  WARNING  ${r.rel} has no <footer> and no markers -- add one or list it in SKIP_FILES`);
  }
  for (const r of by('ambiguous')) {
    console.warn(`  WARNING  ${r.rel} has multiple <footer> elements -- left untouched`);
  }

  const changed = by('updated').length + by('migrated').length;
  console.log(
    `\nFooter: ${by('current').length} current, ${changed} ${check ? 'out of date' : 'rewritten'}, ` +
    `${by('skipped').length} skipped, ${by('no-footer').length + by('ambiguous').length} needing attention ` +
    `(${files.length} pages scanned)`
  );

  if (check && changed > 0) {
    console.error('\nFooters are out of date. Run: node scripts/update-footer.js');
    process.exit(1);
  }
}

main();
